version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    depends_on:
      - server
