import PageLayout from "../../components/PageLayout";

function Home() {
  return (
    <PageLayout>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      {/* <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div>
      <div>Homeeeee</div> */}
    </PageLayout>
  );
}

export default Home;
